version: '3'

services:
  playground.web:
    image: playground.web
    build:
      context: .
      dockerfile: Playground.Web/Dockerfile
    depends_on:
      - playground
      - identity.web

  playground:
    image: playground
    build:
      context: .
      dockerfile: Playground/Dockerfile
    depends_on:
      - identity.web

  identity.web:
    image: identity.web
    build:
      context: .
      dockerfile: Identity.Web/Dockerfile

  identities.data:
    image: ravendb/ravendb
 